# Generated by Django 2.1.7 on 2019-03-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripid',
            new_name='stripeid',
        ),
    ]
