# Generated by Django 2.1.7 on 2019-03-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20190322_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='strip_subscription_id',
            new_name='stripey_subscription_id',
        ),
    ]
