# Generated by Django 2.1.7 on 2019-03-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20190322_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripey_subscription_id',
            new_name='stripen_subscription_id',
        ),
    ]
